# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Kapil"
description:        "Lightweight Personal Blog , Focused on content "

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                ""
author:             "sirkapil"
twitter:
  username:         "kapil_rc"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "http://sirkapil.me"
#baseurl:            "" #For Root Domain
permalink:          /:title/

# Markdown
markdown:           kramdown

# MathJax
mathjax: true

# Responsive Image
cloudinary:
  cloud_name: sirkapil
  verbose: false
  presets:
    default:
      min_width: 360
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    onehalf:
      min_width: 180
      max_width: 800
      fallback_max_width: 400
      steps: 5
      sizes: '(min-width: 50rem) 25rem, 45vw'
      figure: always
      attributes:
        class: onehalf
    onethird:
      min_width: 120
      max_width: 560
      fallback_max_width: 300
      steps: 5
      sizes: '(min-width: 50rem) 17rem, 30vw'
      figure: always
      attributes:
        class: onethird right
    onefourth:
      min_width: 100
      max_width: 400
      fallback_max_width: 200
      steps: 5
      sizes: '(min-width: 50rem) 13rem, 23vw'
      figure: always
      attributes:
        class: onefourth right
    logo:
      min_width: 100
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 55rem) 12.5rem, (min-width: 30rem) 22.5vw, 30vw'
      figure: never
      attributes:
        class: logo
#Background
bg: red

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-cloudinary
