# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Kapil"
description:        "Lightweight Personal Blog , Focused on content "

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//sirkapil.github.io/"
author:             "sirkapil"
twitter:
  username:         "kapil_rc"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "//sirkapil.github.io/Kiko"
#baseurl:            "" #For Root Domain
permalink:          /blog/:title/?ssl

# Markdown
markdown:           kramdown

# MathJax
mathjax: true

# Navigation
nav:
  - name:           "About"
    href:           "/Kiko/about"
  - name:           "Switch"
    href:           "/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag