# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Kapil"
description:        "Lightweight Personal Blog , Focused on content "

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//sirkapil.github.io/"
author:             "sirkapil"
twitter:
  username:         "kapil_rc"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            "//blog-kapil.netlify.com"
#baseurl:            "" #For Root Domain
permalink:          /:title/

# Markdown
markdown:           kramdown

# MathJax
mathjax: true

# Responsive Image
cloudinary:
  cloud_name: "sirkapil"
  verbose: false
  presets:
    default:
      min_width: 600
      max_width: 1000
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    logo:
      min_width: 100
      max_width: 250
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 50rem) 13rem, (min-width: 40rem) 25vw, 45vw'
      figure: never
      attributes:
        class: logo
#Background
bg: red

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-cloudinary
